class HomeConstants {
  static const List<String> allLocations = [
    'Bali',
    'Kota Bandung',
    'Bangka Belitung',
    'Banten',
    'Kota Bekasi',
    'Bengkulu',
    'Kota Bogor',
    'Kota Cilegon',
    'Kota Depok',
    'DI Yogyakarta',
    'DKI Jakarta',
    'Jakarta Barat',
    'Jakarta Selatan',
    'Jakarta Pusat',
    'Jakarta Timur',
    'Jakarta Utara',
    'Jambi',
    'Jawa Barat',
    'Kalimantan Tengah',
    'Kalimantan Timur',
    'Kalimantan Utara',
    'Kepulauan Riau',
    'Lampung',
    'Maluku',
    'Nangroe Aceh D. (NAD)',
    'NTB',
    'NTT',
    'Papua',
    'Kota Serang',
    'Sulawesi Barat',
    'Sulawesi Timur',
    'Sulawesi Tengah',
    'Sulawesi Tenggara',
    'Sulawesi Utara',
    'Sumatera Barat',
    'Sumatera Selatan',
    'Sumatera Utara',
    'Kota Surabaya',
    'Kab. Tangerang',
    'Kota Tangerang',
    'Kab. Tangerang Selatan',
    'Gorontalo',
    'Jabodetabek',
    'Kab. Karawang',
    'Riau',
  ];

  static const List<String> popularLocations = [
    'Jabodetabek',
    'DKI Jakarta',
    'Kalimantan Timur',
    'DI Yogyakarta',
    'Jawa Barat',
    'Sulawesi Selatan',
    'Sumatera Utara',
    'Sumatera Selatan',
    'Jawa Timur',
    'Kalimantan Selatan',
    'Bali',
    'Kalimantan Barat',
  ];
}
